### ISSUE TITLE
影もうちょっと薄くしてほしい...

### ISSUE THREAD

**Issue by touyou** [sasurai-usagi3/nippohub-daily-web#85]
https://github.com/sasurai-usagi3/nippohub-daily-web/blob/7e00a4049b90f1ede6f90141cf1923a27592c517/assets/stylesheets/header.css#L3

例えばこんぐらい（Trelloのカードの影）

```css
box-shadow: 0 1px 0 rgba(9,45,66,.25);
```

あるいは（pubのヘッダーの影）

```css
box-shadow: 0 3px 5px rgba(0,0,0,0.1);
```

**Comment by sasurai-usagi3** [comment]
@touyou PR投げてくれてもいいよー(しばらくWebいじらなさそうだし...)

**Comment by sasurai-usagi3** [comment]
merged https://github.com/sasurai-usagi3/nippohub-daily-web/pull/86
